"""initial

Revision ID: 46dc8f76338f
Revises: 
Create Date: 2026-07-26 20:26:54.881884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46dc8f76338f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_api_key'), 'projects', ['api_key'], unique=True)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('environments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_production', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_project_environment')
    )
    op.create_index(op.f('ix_environments_project_id'), 'environments', ['project_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('framework', sa.String(length=255), nullable=True),
    sa.Column('current_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_project_workflow')
    )
    op.create_index(op.f('ix_workflows_name'), 'workflows', ['name'], unique=False)
    op.create_index(op.f('ix_workflows_project_id'), 'workflows', ['project_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('external_run_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('total_input_tokens', sa.Integer(), nullable=True),
    sa.Column('total_output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('root_span_id', sa.String(length=36), nullable=True),
    sa.Column('user_query', sa.Text(), nullable=True),
    sa.Column('final_output', sa.JSON(), nullable=True),
    sa.Column('failure_type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_environment_id'), 'runs', ['environment_id'], unique=False)
    op.create_index(op.f('ix_runs_external_run_id'), 'runs', ['external_run_id'], unique=False)
    op.create_index(op.f('ix_runs_failure_type'), 'runs', ['failure_type'], unique=False)
    op.create_index(op.f('ix_runs_started_at'), 'runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_index(op.f('ix_runs_workflow_id'), 'runs', ['workflow_id'], unique=False)
    op.create_table('eval_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_behavior', sa.Text(), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('gold_output', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_cases_project_id'), 'eval_cases', ['project_id'], unique=False)
    op.create_table('spans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('parent_span_id', sa.String(length=36), nullable=True),
    sa.Column('span_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parent_span_id'], ['spans.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spans_parent_span_id'), 'spans', ['parent_span_id'], unique=False)
    op.create_index(op.f('ix_spans_run_id'), 'spans', ['run_id'], unique=False)
    op.create_index(op.f('ix_spans_span_type'), 'spans', ['span_type'], unique=False)
    op.create_index(op.f('ix_spans_started_at'), 'spans', ['started_at'], unique=False)
    op.create_index(op.f('ix_spans_status'), 'spans', ['status'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('span_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['span_id'], ['spans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_run_id'), 'annotations', ['run_id'], unique=False)
    op.create_index(op.f('ix_annotations_span_id'), 'annotations', ['span_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('span_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['span_id'], ['spans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_run_id'), 'artifacts', ['run_id'], unique=False)
    op.create_index(op.f('ix_artifacts_span_id'), 'artifacts', ['span_id'], unique=False)
    op.create_table('eval_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('eval_case_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_version', sa.String(length=50), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('judge_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['eval_case_id'], ['eval_cases.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_results_eval_case_id'), 'eval_results', ['eval_case_id'], unique=False)
    op.create_table('retrieved_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('span_id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=500), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('chunk_id', sa.String(length=255), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('content_snippet', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['span_id'], ['spans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieved_documents_span_id'), 'retrieved_documents', ['span_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieved_documents_span_id'), table_name='retrieved_documents')
    op.drop_table('retrieved_documents')
    op.drop_index(op.f('ix_eval_results_eval_case_id'), table_name='eval_results')
    op.drop_table('eval_results')
    op.drop_index(op.f('ix_artifacts_span_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_run_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_annotations_span_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_run_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_spans_status'), table_name='spans')
    op.drop_index(op.f('ix_spans_started_at'), table_name='spans')
    op.drop_index(op.f('ix_spans_span_type'), table_name='spans')
    op.drop_index(op.f('ix_spans_run_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_parent_span_id'), table_name='spans')
    op.drop_table('spans')
    op.drop_index(op.f('ix_eval_cases_project_id'), table_name='eval_cases')
    op.drop_table('eval_cases')
    op.drop_index(op.f('ix_runs_workflow_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_started_at'), table_name='runs')
    op.drop_index(op.f('ix_runs_failure_type'), table_name='runs')
    op.drop_index(op.f('ix_runs_external_run_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_environment_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_workflows_project_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_name'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_environments_project_id'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_api_key'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
